TestPlantilla/Models/ColaboradorView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestPlantilla.Models
{
    public class ColaboradorView
    {
        public int run { get; set; }
        public string rut { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<int> edad { get; set; }
        public string cargo { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> valorHoraExtra { get; set; }
    }
}

TestPlantilla/Models/colaborador.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public colaborador()
        {
            this.colaboradorHojaRuta = new HashSet<colaboradorHojaRuta>();
        }
    
        public int run { get; set; }
        public string rut { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public Nullable<int> edad { get; set; }
        public string cargo { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> valorHoraExtra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colaboradorHojaRuta> colaboradorHojaRuta { get; set; }
    }
}

TestPlantilla/Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestPlantilla.Models;

namespace TestPlantilla.Controllers
{
    public class ColaboradorController : Controller
    {
        dimacodevEntities dd = new dimacodevEntities();
        // GET: Colaborador
        public ActionResult Index()
        {
            ViewBag.Title = "Colaboradores";
            return View();
        }

        public JsonResult GetColaboradores()
        {
            List<ColaboradorView> colaborador = dd.colaborador.Select(c => new ColaboradorView
            {
                run = c.run,
                rut = c.rut,
                nombre = c.nombre,
                apellidoPaterno = c.apellidoPaterno,
                apellidoMaterno = c.apellidoMaterno,
                edad = c.edad,
                cargo = c.cargo,
                telefono = c.telefono,
                valorHoraExtra = c.valorHoraExtra
            }).ToList();
            return Json(new { data = colaborador }, JsonRequestBehavior.AllowGet);
        }
    }
}

TestPlantilla/Views/Colaborador/Eliminar.cshtml
@model TestPlantilla.Models.ColaboradorView
<h2>Save</h2>
@using (Html.BeginForm("Eliminar", "Colaborador", FormMethod.Post, new { id = "popupForm" }))
{
        @Html.HiddenFor(c => c.run)

    <div class="form-group">
        <label>R.U.T.</label>
        <p>@Model.rut</p>
    </div>
    <div class="form-group">
        <label>Nombre</label>
        <p>@Model.nombre</p>
    </div>
    <div class="form-group">
        <label>A. Paterno</label>
        <p>@Model.apellidoPaterno</p>
    </div>
    <div class="form-group">
        <label>A. Materno</label>
        <p>@Model.apellidoMaterno</p>
    </div>
    <div class="form-group">
        <label>Edad</label>
        <p>@Model.edad</p>
    </div>
    <div class="form-group">
        <label>Cargo</label>
        <p>@Model.cargo</p>
    </div>
    <div class="form-group">
        <label>Teléfono</label>
        <p>@Model.telefono</p>
    </div>
    <div class="form-group">
        <label>Valor H/E</label>
        <p>@Model.valorHoraExtra</p>
    </div>
    <div>
        <input type="submit" value="Guardar" />
    </div>

TestPlantilla/Views/Colaborador/Guardar.cshtml
@model TestPlantilla.Models.ColaboradorView
<h2>Save</h2>
@using (Html.BeginForm("Guardar", "Colaborador", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.run > 0)
    {
        @Html.HiddenFor(c => c.run)
    }
    else
    {
        <div class="form-group">
            <label>R.U.N.</label>
            @Html.TextBoxFor(c => c.run, new { @class = "form-control" })
            @Html.ValidationMessageFor(c => c.run)
        </div>
    }

    <div class="form-group">
        <label>R.U.T.</label>
        @Html.TextBoxFor(c => c.rut, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.rut)
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(c => c.nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.nombre)
    </div>
    <div class="form-group">
        <label>A. Paterno</label>
        @Html.TextBoxFor(c => c.apellidoPaterno, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.apellidoPaterno)
    </div>
    <div class="form-group">
        <label>A. Materno</label>
        @Html.TextBoxFor(c => c.apellidoMaterno, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.apellidoMaterno)
    </div>
    <div class="form-group">
        <label>Edad</label>
        @Html.TextBoxFor(c => c.edad, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.edad)
    </div>
    <div class="form-group">
        <label>Cargo</label>
        @Html.TextBoxFor(c => c.cargo, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.cargo)
    </div>
    <div class="form-group">
        <label>Teléfono</label>
        @Html.TextBoxFor(c => c.telefono, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.telefono)
    </div>
    <div class="form-group">
        <label>Valor H/E</label>
        @Html.TextBoxFor(c => c.valorHoraExtra, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.valorHoraExtra)
    </div>
    <div>
        <input type="submit" value="Guardar" />
    </div>
}

TestPlantilla/Views/Colaborador/Index.cshtml
@model TestPlantilla.Models.ColaboradorView
@{
<div class="container">
    <div class="row">
        <div class="col">
            <h3 class="title-5 m-b-35" style="margin-top: 1em;">Gestión de colaboradores</h3>
        </div>
        <div class="col">
            <a class="btn btn-success float-right" href="#" style="margin-top: 1em; color: white;">
                <i class="fas fa-plus"></i>&nbsp;&nbsp;Agregar colaborador
            </a>
        </div>            
    </div>
    
    <table id="tablaColaborador" class="table table-bordered table-striped tablecontainer" style="width: 100%">
        <thead>
            <tr>
                <th>R.U.N.</th>
                <th>R.U.T.</th>
                <th>Nombre</th>
                <th>A. Paterno</th>
                <th>A. Materno</th>
                <th>Edad</th>
                <th>Cargo</th>
                <th>Teléfono</th>
                <th>Valor H/E</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
    </table>
</div>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            var oTable = $('#tablaColaborador').DataTable({
                "ajax": {
                    "url": '/Colaborador/GetColaboradores',
                    "type": "get",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "run" },
                    { "data": "rut" },
                    { "data": "nombre" },
                    { "data": "apellidoPaterno" },
                    { "data": "apellidoMaterno" },
                    { "data": "edad" },
                    { "data": "cargo" },
                    { "data": "telefono" },
                    { "data": "valorHoraExtra" },
                    {
                        "data": "run", "render": function (data) {
                            return '<a class="btn btn-success popup" href="#"><i class="fas fa-edit"></i></a>';
                        }
                    },
                    {
                        "data": "run", "render": function (data) {
                            return '<a class="btn btn-danger popup" href="#"><i class="fas fa-trash"></i></a>';
                        }
                    }
                ]
            })
        })
    </script>    
}